# Generated by Django 5.2.5 on 2025-10-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('players', models.IntegerField()),
                ('age', models.FloatField()),
                ('possession', models.FloatField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('penalty_kicks', models.IntegerField()),
                ('penalty_kick_attempts', models.IntegerField()),
                ('yellows', models.IntegerField()),
                ('reds', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/')),
            ],
        ),
    ]
