# Generated by Django 5.2.7 on 2025-11-26 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('publish_time', models.DateField()),
                ('content', models.TextField()),
                ('thumbnail', models.URLField(blank=True, default='images/thumbnails/default.png')),
                ('featured', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Transfer', 'Transfer'), ('Injury Update', 'Injury Update'), ('Match Result', 'Match Result'), ('Manager News', 'Manager News'), ('Player Award', 'Player Award'), ('Thoughts', 'Thoughts'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kgs', models.FloatField(blank=True, null=True)),
                ('positions', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('overall_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('value_euro', models.FloatField(blank=True, null=True)),
                ('wage_euro', models.FloatField(blank=True, null=True)),
                ('preferred_foot', models.CharField(max_length=10, null=True)),
                ('international_reputation', models.PositiveIntegerField(blank=True, null=True)),
                ('weak_foot', models.PositiveIntegerField(blank=True, null=True)),
                ('skill_moves', models.PositiveIntegerField(blank=True, null=True)),
                ('release_clause_euro', models.FloatField(blank=True, null=True)),
                ('national_team', models.CharField(max_length=100, null=True)),
                ('finishing', models.PositiveIntegerField(blank=True, null=True)),
                ('heading_accuracy', models.PositiveIntegerField(blank=True, null=True)),
                ('short_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('volleys', models.PositiveIntegerField(blank=True, null=True)),
                ('dribbling', models.PositiveIntegerField(blank=True, null=True)),
                ('long_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('ball_control', models.PositiveIntegerField(blank=True, null=True)),
                ('acceleration', models.PositiveIntegerField(blank=True, null=True)),
                ('sprint_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('agility', models.PositiveIntegerField(blank=True, null=True)),
                ('jumping', models.PositiveIntegerField(blank=True, null=True)),
                ('stamina', models.PositiveIntegerField(blank=True, null=True)),
                ('strength', models.PositiveIntegerField(blank=True, null=True)),
                ('long_shots', models.PositiveIntegerField(blank=True, null=True)),
                ('vision', models.PositiveIntegerField(blank=True, null=True)),
                ('penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('marking', models.PositiveIntegerField(blank=True, null=True)),
                ('standing_tackle', models.PositiveIntegerField(blank=True, null=True)),
                ('sliding_tackle', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('players', models.IntegerField()),
                ('age', models.FloatField(null=True)),
                ('possession', models.FloatField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('penalty_kicks', models.IntegerField(null=True)),
                ('penalty_kick_attempts', models.IntegerField(null=True)),
                ('yellows', models.IntegerField()),
                ('reds', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=20)),
                ('match_date', models.DateField()),
                ('league', models.CharField(default='Unknown', max_length=100)),
                ('full_time_home_goals', models.IntegerField()),
                ('full_time_away_goals', models.IntegerField()),
                ('full_time_result', models.CharField(max_length=1)),
                ('half_time_home_goals', models.IntegerField()),
                ('half_time_away_goals', models.IntegerField()),
                ('half_time_result', models.CharField(max_length=1)),
                ('home_shots', models.IntegerField()),
                ('away_shots', models.IntegerField()),
                ('home_shots_on_target', models.IntegerField()),
                ('away_shots_on_target', models.IntegerField()),
                ('home_corners', models.IntegerField()),
                ('away_corners', models.IntegerField()),
                ('home_fouls', models.IntegerField()),
                ('away_fouls', models.IntegerField()),
                ('home_yellow_cards', models.IntegerField()),
                ('away_yellow_cards', models.IntegerField()),
                ('home_red_cards', models.IntegerField()),
                ('away_red_cards', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='main.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='main.team')),
            ],
        ),
    ]
