# Generated by Django 5.2.7 on 2025-10-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kgs', models.FloatField(blank=True, null=True)),
                ('positions', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('overall_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('value_euro', models.FloatField(blank=True, null=True)),
                ('wage_euro', models.FloatField(blank=True, null=True)),
                ('preferred_foot', models.CharField(max_length=10, null=True)),
                ('international_reputation', models.PositiveIntegerField(blank=True, null=True)),
                ('weak_foot', models.PositiveIntegerField(blank=True, null=True)),
                ('skill_moves', models.PositiveIntegerField(blank=True, null=True)),
                ('release_clause_euro', models.FloatField(blank=True, null=True)),
                ('national_team', models.CharField(max_length=100, null=True)),
                ('finishing', models.PositiveIntegerField(blank=True, null=True)),
                ('heading_accuracy', models.PositiveIntegerField(blank=True, null=True)),
                ('short_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('volleys', models.PositiveIntegerField(blank=True, null=True)),
                ('dribbling', models.PositiveIntegerField(blank=True, null=True)),
                ('long_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('ball_control', models.PositiveIntegerField(blank=True, null=True)),
                ('acceleration', models.PositiveIntegerField(blank=True, null=True)),
                ('sprint_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('agility', models.PositiveIntegerField(blank=True, null=True)),
                ('jumping', models.PositiveIntegerField(blank=True, null=True)),
                ('stamina', models.PositiveIntegerField(blank=True, null=True)),
                ('strength', models.PositiveIntegerField(blank=True, null=True)),
                ('long_shots', models.PositiveIntegerField(blank=True, null=True)),
                ('vision', models.PositiveIntegerField(blank=True, null=True)),
                ('penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('marking', models.PositiveIntegerField(blank=True, null=True)),
                ('standing_tackle', models.PositiveIntegerField(blank=True, null=True)),
                ('sliding_tackle', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('players', models.IntegerField()),
                ('age', models.FloatField()),
                ('possession', models.FloatField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('penalty_kicks', models.IntegerField()),
                ('penalty_kick_attempts', models.IntegerField()),
                ('yellows', models.IntegerField()),
                ('reds', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/')),
            ],
        ),
    ]
