# Generated by Django 5.2.7 on 2025-10-24 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=20)),
                ('match_date', models.DateField()),
                ('league', models.CharField(default='Unknown', max_length=100)),
                ('full_time_home_goals', models.IntegerField()),
                ('full_time_away_goals', models.IntegerField()),
                ('full_time_result', models.CharField(max_length=1)),
                ('half_time_home_goals', models.IntegerField()),
                ('half_time_away_goals', models.IntegerField()),
                ('half_time_result', models.CharField(max_length=1)),
                ('home_shots', models.IntegerField()),
                ('away_shots', models.IntegerField()),
                ('home_shots_on_target', models.IntegerField()),
                ('away_shots_on_target', models.IntegerField()),
                ('home_corners', models.IntegerField()),
                ('away_corners', models.IntegerField()),
                ('home_fouls', models.IntegerField()),
                ('away_fouls', models.IntegerField()),
                ('home_yellow_cards', models.IntegerField()),
                ('away_yellow_cards', models.IntegerField()),
                ('home_red_cards', models.IntegerField()),
                ('away_red_cards', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='main.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='main.team')),
            ],
        ),
    ]
