# Generated by Django 5.2.5 on 2025-12-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='bookmarked_by',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='match',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='news',
        ),
        migrations.AddField(
            model_name='forum',
            name='quoted_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_by', to='main.forum'),
        ),
    ]
