# Generated by Django 5.2.7 on 2025-10-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
