# Generated by Django 5.2.7 on 2025-10-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_comment_reply_thread_comment_thread_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
