# Generated by Django 5.2.7 on 2025-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='penalty_kick_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='penalty_kicks',
            field=models.IntegerField(null=True),
        ),
    ]
