# Generated by Django 5.2.7 on 2025-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_person_role_forum_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='main.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_corners',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_fouls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_shots_on_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_yellow_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='full_time_away_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='full_time_home_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='full_time_result',
            field=models.CharField(default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='half_time_away_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='half_time_home_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='half_time_result',
            field=models.CharField(default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_corners',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_fouls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_shots_on_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_yellow_cards',
            field=models.IntegerField(default=0),
        ),
    ]
