# Generated by Django 5.2.5 on 2025-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_forum_bookmarked_by_remove_forum_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_forums', to='main.person'),
        ),
    ]
