# Generated by Django 5.2.7 on 2025-10-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_team_age_alter_team_penalty_kick_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_pictures/'),
        ),
    ]
