# Generated by Django 5.2.7 on 2025-12-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_liked_by_alter_match_away_corners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_news', to='main.person'),
        ),
    ]
