# Generated by Django 5.2.5 on 2025-12-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_forum_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
    ]
